services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "54322:5432"
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "54333:80"
    depends_on:
      - postgres
